### ISSUE TITLE
package-lock.json should not be included in version control

### ISSUE THREAD

**Issue by YassineElbouchaibi** [CSS-Electronics/cancloud#22]
package-lock.json  should be added to the git ignore.

It causes `npm install` to install whatever is in it. This includes old versions and packages not in package.json such as electron.

For the time being I delete it on my side before installing.

**Comment by MatinF** [comment]
Thanks for the feedback, this should be updated now, but let me know if it still does not work as intended. Also updated the version number in the package.json

**Comment by YassineElbouchaibi** [comment]
I think the actual file should be deleted from the github repo as well.
