### ISSUE TITLE
Trouble building with a docker file

### ISSUE THREAD

**Issue by tarmacx** [CSS-Electronics/cancloud#24]
I'm trying to build the image under windows with WSL2 and a dockerfile based on the officiel node image and it always fails for different reasons.
Tried node 12, 14, 16 and 18 and they all fail.

Most common error I see is 
`
# npm install
npm notice
npm notice New major version of npm available! 8.19.4 -> 9.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.1
npm notice Run npm install -g npm@9.8.1 to update!
npm notice
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: cancloud@05.08.04
npm ERR! Found: webpack@4.46.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^4.22.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^1.9.11" from purifycss-webpack-plugin@2.0.3
npm ERR! node_modules/purifycss-webpack-plugin
npm ERR!   dev purifycss-webpack-plugin@"^2.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-08-02T21_09_52_503Z-debug-0.log
`

**Comment by MatinF** [comment]
If the goal is simply to self-host CANcloud, you can use the latest built release. We are unfortunately not able to support on the build process for different systems, but the pre built version can be customized in terms of logo and CSS and simply extracted onto your web server

**Comment by tarmacx** [comment]
Hi MatinF, 

I understand perfectly. Sadly I really need more customization. 
Can you just add to the documentation what you use to build yours so we have a better starting point on our side ?
Things like Node version, OS, or any other that will just help us figure it out ourselves.

Regards

**Comment by MatinF** [comment]
When building on our side we use Node v16.16.0 and Windows 10. It may be that you'll need to use `--force` when installing the dependencies. Let me know if this helps resolve it?

**Comment by tarmacx** [comment]
I'm using windows 10 but I build running a Dockerfile with node:16... it's really the sharp modeule that seems to be the main issue. 
`
npm ERR! code 1
npm ERR! path /app/node_modules/favicons/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c -- (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! make: Entering directory '/app/node_modules/favicons/node_modules/sharp/build'
npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! make: Leaving directory '/app/node_modules/favicons/node_modules/sharp/build'
npm ERR! info sharp Using cached /root/.npm/_libvips/libvips-8.7.4-linux-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.20.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/app/node_modules/favicons/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/16.20.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.20.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.20.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/favicons/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
npm ERR! <command-line>: note: this is the location of the previous definition
npm ERR! In file included from /root/.cache/node-gyp/16.20.1/include/node/v8.h:30,
npm ERR!                  from /root/.cache/node-gyp/16.20.1/include/node/node.h:73,
npm ERR!                  from ../src/common.cc:22:
npm ERR! /root/.cache/node-gyp/16.20.1/include/node/v8-internal.h: In function 'void v8::internal::PerformCastCheck(T*)':
npm ERR! /root/.cache/node-gyp/16.20.1/include/node/v8-internal.h:492:38: error: 'remove_cv_t' is not a member of 'std'
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                       ^~~~~~~~~~~
npm ERR! /root/.cache/node-gyp/16.20.1/include/node/v8-internal.h:492:38: note: suggested alternative: 'remove_cv'
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                       ^~~~~~~~~~~
npm ERR!                                       remove_cv
npm ERR! /root/.cache/node-gyp/16.20.1/include/node/v8-internal.h:492:38: error: 'remove_cv_t' is not a member of 'std'
npm ERR! /root/.cache/node-gyp/16.20.1/include/node/v8-internal.h:492:38: note: suggested alternative: 'remove_cv'
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                       ^~~~~~~~~~~
npm ERR!                                       remove_cv
npm ERR! /root/.cache/node-gyp/16.20.1/include/node/v8-internal.h:492:50: error: template argument 2 is invalid
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                                   ^
npm ERR! /root/.cache/node-gyp/16.20.1/include/node/v8-internal.h:492:63: error: '::Perform' has not been declared
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                                                ^~~~~~~
npm ERR! /root/.cache/node-gyp/16.20.1/include/node/v8-internal.h:492:63: note: suggested alternative: 'perror'
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                                                ^~~~~~~
npm ERR!                                                                perror
npm ERR! make: *** [sharp.target.mk:140: Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Linux 5.10.102.1-microsoft-standard-WSL2
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /app/node_modules/favicons/node_modules/sharp
npm ERR! gyp ERR! node -v v16.20.1
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok
`

**Comment by tarmacx** [comment]
I know you dont want to support building for all possible configuration but do you think it would be possible to maybe provide a DockerFile that perform the building as a base. That way everybody could have a stable and identical starting point on which to build.

My current DockerFile is a mess because I tried so many things and most of them are now commented but you can have a look at it here:

```
# stage1 as builder
#FROM node:latest as builder
#FROM node:current-alpine as builder
FROM node:16 as builder

#ENV SHARP_IGNORE_GLOBAL_LIBVIPS=1

#https://stackoverflow.com/questions/62554991/how-do-i-install-python-on-alpine-linux
# Install python/pip
#ENV PYTHONUNBUFFERED=1
#RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
#RUN python3 -m ensurepip
#RUN pip3 install --no-cache --upgrade pip setuptools


#RUN apk add --update python3 make g++\
#   && rm -rf /var/cache/apk/*

RUN apt-get update
RUN apt-get install -y python3

WORKDIR /app

# copy the package.json to install dependencies
COPY package*.json ./

#Test
#RUN npm i sharp

# Install the dependencies and make the folder
#
#RUN npm install --legacy-peer-deps
#RUN npm install --arch=x64 --platform=linux  --libc=musl sharp --legacy-peer-deps && mkdir /react-ui && mv ./node_modules ./react-ui

#RUN npm install --arch=x64 --platform=linux --libc=glibc --legacy-peer-deps --verbose --foreground-scripts && mkdir /react-ui && mv ./node_modules ./react-ui
#RUN npm run build

#WORKDIR /app

#COPY . .

# Build the project and copy the files
#RUN npm run build


#FROM nginx:alpine

#!/bin/sh

#COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf

## Remove default nginx index page
#RUN rm -rf /usr/share/nginx/html/*

# Copy from the stahg 1
#COPY --from=builder /react-ui/build /usr/share/nginx/html

#EXPOSE 3000 80

#ENTRYPOINT ["nginx", "-g", "daemon off;"]
```

**Comment by MatinF** [comment]
I'm afraid Docker is not my expertise. I am also having problems building CANcloud anew from a clean github pull, so I believe some work needs to be done in order to identify some issues with dependencies. For example, it appears the `sharp` module is causing issues on my end when attempting to install on Windows, maybe related to the build tools I have. For some reason the latest build is working in the original source folder without issues on the same PC.

I've attached the package-lock.json from the working folder. Maybe that helps. If you have some suggestions for other information that could help in this regard I can try and provide it from the working folder.

[package-lock.zip](https://github.com/CSS-Electronics/cancloud/files/12253340/package-lock.zip)

**Comment by tarmacx** [comment]
I managed to build it if I skip sharp scripts...  npm install --ignore-scripts sharp...
Also tried a bit with npm install --legacy-peer-deps

**Comment by tarmacx** [comment]
This works. This can get a starting point for your DockerFile... now if you have ways to test that everything works...

```
# stage1 as builder
FROM node:16 as builder

WORKDIR /app

# copy the package.json to install dependencies
COPY package*.json ./

# Install the dependencies and make the folder
RUN npm install --ignore-scripts

#Build phase
WORKDIR /app
COPY . .

# Build the project and copy the files
RUN npm run build

#Web server
FROM nginx:latest

#!/bin/sh
COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf

## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

# Copy from the stage 1
COPY --from=builder /app/site /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
```

**Comment by tarmacx** [comment]
In my ongoing progress to resolve this I removed the purifycss and related plugins as there are in the package.json but never used in the program. This removes the dependency issue. I'v not retried a compilation yet.

**Comment by tarmacx** [comment]
```
    // if the user selects specific devices (devicesFilesInput) show these. If no selection, show up to X devices by default
    var devicesFiles = devicesFilesInput != undefined && devicesFilesInput.length != 0 ? devicesFilesInput : devices.slice(0, devicesFilesDefaultMax);
```

**Comment by MatinF** [comment]
Arh I see now, I misunderstood the issue. This is working as intended: To avoid excessively loading data from S3, the default view will only populate if there are less than 10 devices. For more devices you'll have to manually specify that you wish to update the view. This could be changed to show the top 10, but that would be a bit arbitrary.

**Comment by MatinF** [comment]
We'll look into eventually cleaning up the packages.json, thanks

**Comment by MatinF** [comment]
We incorporated your suggestions (and Dockerfile) now, along with an update to `favicons-webpack-plugin@4.2.0` which seems to fix the issue with `sharp` so as to avoid the need for the `ignore-scripts` aspect. If any further issues let us know - thanks for your detective work on this!
