### ISSUE TITLE
Data related infos not working with latest minio version

### ISSUE THREAD

**Issue by tarmacx** [CSS-Electronics/cancloud#25]
It seems like the data related does not work anymore in the latest version of minio. I jumped from a ayear old revision so it's hard to pinpoint exactly where it startted to fail: 
![image](https://github.com/CSS-Electronics/cancloud/assets/13239306/18c8860f-9c7b-48e0-b3eb-a986d26d1c4c)

It's behaving the same on my local version, your online copy and a self build with an nginx server/dockerfile.

**Comment by MatinF** [comment]
Can you clarify what version of MinIO you're using? And have you replicated the issue with the version we host below?
https://canlogger.csselectronics.com/canedge-getting-started/ce2/transfer-data/s3-server/local-server/#setting-up-a-local-minio-server

**Comment by tarmacx** [comment]
I used that one for the screenshot: https://canlogger.csselectronics.com/cancloud/#/status-dashboard/
I also tried with a locally downloaded version and it does the same.
Tried with Chrome (default), Edge and Firefox and it's the same.
Using: minio/minio:RELEASE.2023-07-21T21-12-44Z

**Comment by tarmacx** [comment]
Do you need more informations ? I can do some more tests if you want. Or try with my dev instance in docker as explained in issue #24

**Comment by MatinF** [comment]
We'll have to do some testing of this, it's not something that can be quickly solved necessarily. But we'll look into this next week.

**Comment by tarmacx** [comment]
I'm not sure the issue is with minio... I made it work by changing the max device files in actions.js:
![image](https://github.com/CSS-Electronics/cancloud/assets/13239306/f38c6ac5-0a58-4547-a433-c02573440739)
To something higher because I had 13 devices and the max was 10:
![image](https://github.com/CSS-Electronics/cancloud/assets/13239306/e2588581-1d96-4273-8c3b-e6d6d970388a)

Instead of returning an empty array if it's higher than defaultmax should we just return the top ones up to the limit ?

**Comment by MatinF** [comment]
Arh I see now, I misunderstood the issue. This is working as intended: To avoid excessively loading data from S3, the default view will only populate if there are less than 10 devices. For more devices you'll have to manually specify that you wish to update the view. This could be changed to show the top 10, but that would be a bit arbitrary.

**Comment by tarmacx** [comment]
I understand but the fact is that if for example I have 13 devices, and I select "weekly" only 7 devices updated recently so only 7 items is displayed in the device list at the bottom. This script uses the main device list for this query so it still takes the 13 devices thus returning an empty array and doing nothing.

Wouldnt it be better to use the device list filtered in the table so I have 7 devices (which is under the 10 limit)?
Also having this limit as a parameter of some sort would help for specific cases ? For example we move the files from the main bucket once processed so we never have an issue of slowing down this dashboard because the load of files to be processed is minimal.
And lastly, maybe an error message instead of nothing ? Like "Too many devices to load data upload informations"

**Comment by MatinF** [comment]
Thanks for the suggestions - we'll review and consider adjusting the behavior in an upcoming update

**Comment by MatinF** [comment]
We decided for now in the team to not change this - but since the building of CANcloud should now be simpler, it can be modified in the source code of a custom build if preferred
